name: PR check

on:
  pull_request:
    branches: [main]

concurrency:
  group: pr-check-${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.2.2
      - uses: actions/setup-node@v4.4.0
        with:
          node-version: 22
          cache: npm
      - run: npm ci
      - run: npx astro check
      - run: npm run build
